# Generated by Django 5.0.1 on 2024-03-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stockzz_remove_stockz_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockzz',
            old_name='productname',
            new_name='names',
        ),
    ]
