# Generated by Django 5.0.1 on 2024-03-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_productname_stockzz_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockz',
            name='pname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
