from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('',views.home,name='home'),
    path('detail',views.detail,name='detail'),
    path('contact',views.contact,name='contact'),
    path('shops',views.shops,name='shops'),
    path('loginpage',views.loginpage,name='loginpage'),
    path('registerpage',views.registerpage,name='registerpage'),
    path('adminindexpage',views.adminndexpage,name='adminindexpage'),
    path('add_product', views.add_product, name='add_product'),
    path('viewproduct', views.viewproduct, name='viewproduct'),
    path('update_product/<int:id>/', views.update_product, name='update_product'),
    path('del_product/<int:id>/', views.del_product, name='del_product'),
    path('add_complaint',views.add_complaint,name='add_complaint'),
    path('complaint_success',views.complaint_success,name='complaint_success'),
    path('view_complaints',views.view_complaints,name='view_complaints'),
    path("logout_request", views.logout_request, name="logout_request"),
    path('pro/<int:id>/',views.pro,name='pro'),
    path('view_cart', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add, name='add'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    #path('checkout', views.checkout, name='checkout'),
    path('test',views.test,name='test'),
    path('config/', views.stripe_config),
    path('create-checkout-session/', views.create_checkout_session),
    path('payment', views.payment,name='payment'),
    path('payment_success',views.payment_success,name='payment_success'),
    path('payment_status',views.payment_status,name='payment_status'),
    path('cancelled/', views.cancelled,name='cancelled'),
    path('process_dummy_payment',views.process_dummy_payment,name='process_dummy_payment'),
    path('process_pay',views.process_pay,name='process_pay'),
    path('payment_successful',views.payment_successful,name='payment_successful'),
    #path('payment_stat',views.payment_stat,name='payment_stat'),
    path('view_paystatus',views.view_paystatus,name='view_paystatus'),
    path('rate/<int:product_id>/', views.rate, name='rate'),
    path('Review_rate/<int:product_id>/',views.Review_rate,name='Review_rate'),
    path('review_success',views.review_success,name='review_success'),
    path('view_reviews', views.view_reviews, name='view_reviews'),
    path('reviews', views.reviews, name='reviews'),
    path('view_booking', views.view_booking, name='view_booking'),
    path('admin_view_cart', views.admin_view_cart, name='admin_view_cart'),
    path('custorders', views.custorders, name='custorders'),
    path('addorder', views.addorder, name='addorder'),
    path('vieworder', views.vieworder, name='vieworder'),
    path('updateorder/<int:id>/', views.updateorder, name='updateorder'),
    
    
]
